name: Update RPi repository

on:
  workflow_dispatch:
    inputs:
      release:
        description: Create release?
        required: true
        type: boolean

env:
  RELFILE: rpi_repo.tar.gz
  RELNOTESFILE: relnotes.txt

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Prepare tmp directories
        run: |
          mkdir -p dl/artifacts
          mkdir dist

      - name: Download packages
        uses: dawidd6/action-download-artifact@v4
        with:
          workflow: create_dpkg_test2.yml
          workflow_conclusion: success
          path: dl/artifacts
          name: "raspbian|raspberrypi|debian"
          name_is_regexp: true

      - name: List artifacts
        run: |
          ls -rl dl/artifacts
