name: Update Debian packages branch

on:
  workflow_dispatch:
    inputs:
      release:
        description: Push new packages?
        required: true
        type: boolean

jobs:
  update_dpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: dpkg

      - name: Prepare directories
        run: |
          mkdir dl
          mkdir -p owntone-server
          mkdir -p airptpd

      - name: Download packages
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: create_dpkg_test2.yml
          workflow_conclusion: success
          path: dl
          name: "debian"
          name_is_regexp: true

      - name: Add incoming packages
        working-directory: dl
        run: |
          ls -lR ..
          find -name owntone_*.deb -type f -print0 | xargs -0 cp --update=none --target-directory=../owntone-server
          find -name airptpd_*.deb -type f -print0 | xargs -0 cp --update=none --target-directory=../airptpd
          ls -lR ..

      # The GH action email is from https://github.com/orgs/community/discussions/26560
      - name: Commit and push updated assets
        if: ${{ github.event.inputs.release == 'true' }}
        run: |
          git add owntone-server/
          git add airptpd/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Add Debian packages"
          git push
