name: Update Debian packages branch

on:
  workflow_dispatch:

jobs:
  update_dpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: dpkg

      - name: Prepare directories
        run: |
          mkdir dl
          mkdir -p owntone-server
          mkdir -p airptpd

      - name: Download packages
        uses: actions/download-artifact@v8
        with:
          path: dl
          pattern: "debian"

      - name: Add incoming packages
        working-directory: dl
        run: |
          ls -lR ..
          find owntone_*.deb -type f -print0 | xargs -0 cp --update=none --target-directory=../owntone-server
          find airptpd_*.deb -type f -print0 | xargs -0 cp --update=none --target-directory=../airptpd
          ls -lR ..
