name: Update RPi repository

on:
  workflow_dispatch:
    inputs:
      release:
        description: Create release?
        required: true
        type: boolean

env:
  RELFILE: rpi_repo.tar.gz
  RELNOTESFILE: relnotes.txt

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Prepare tmp directories
        run: |
          mkdir dl
          mkdir dist

      - name: Download packages
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create_dpkg_test2.yml
          workflow_conclusion: success
          path: dl

      # Moves from e.g. dl/raspberrypi-bullseye-arm64 to repo/rpi/incoming
      - name: Add incoming packages
        working-directory: repo/rpi
        env:
          DPKGDIR: ../../dl
        run: |
          ls -l ../../dl
