name: Update RPi repository

on:
  workflow_dispatch:
    inputs:
      owntone-server:
        required: true
        type: boolean
      airptpd:
        required: true
        type: boolean
      release:
        description: Create release?
        required: true
        type: boolean

env:
  RELFILE: rpi_repo.tar.gz
  RELNOTESFILE: relnotes.txt
  ARTIFACTSDIR: dl/artifacts

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Prepare tmp directories
        run: |
          mkdir -p $ARTIFACTSDIR
          mkdir dist

      - name: Mock dl repo
        run: |
          mkdir -p repo/rpi/var/incoming

      - name: Download packages
        uses: dawidd6/action-download-artifact@v21
        with:
          workflow: create_dpkg_test2.yml
          workflow_conclusion: success
          path: $ARTIFACTSDIR
          name: "raspbian|raspberrypi|debian"
          name_is_regexp: true

      - name: List artifacts
        run: |
          ls -lR $ARTIFACTSDIR

      - name: Add owntone debs
        if: ${{ github.event.inputs.owntone-server == 'true' }}
        run: |
          find $ARTIFACTSDIR/owntone* -type f -print0 | xargs -0 cp --update=none --target-directory=repo/rpi/var/incoming

      - name: Add airptpd debs
        if: ${{ github.event.inputs.airptpd == 'true' }}
        run: |
          find $ARTIFACTSDIR/airptpd* -type f -print0 | xargs -0 cp --update=none --target-directory=repo/rpi/var/incoming

      - name: Process incoming packages
        working-directory: repo/rpi
        run: |
          ls -l var/incoming
